### PR TITLE
Publish charm to 2.8/* track

### PR DESCRIPTION
**Pull request by Thanhphan1147**
We are publishing the new haproxy charm to `2.8/{stable|edge}`. The reason for this is we have 2 versions of the haproxy charm co-existing at the same time. For now we've decided that the "legacy" charm which is at legacy/main will stay on latest/* and the new charm will be at 2.8/* for the moment since it provides haproxy v2.8. This PR updates the publish and promote target of relevant workflows.

### Checklist

- [x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [x] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [x] The documentation is generated using `src-docs`
- [x] The documentation for charmhub is updated
- [x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

### CODE REVIEW

**Comment by Thanhphan1147** [comment]
Hi @mthaddon, @gregory-schiano, can you take a look at this trivial PR updating the publish and promote target? Thanks!

**Review by arturo-seijas — COMMENTED** [review]
This charm is still under heavy development, as I understand it. Why publishing to something different than  "latest"?

**Comment by Thanhphan1147** [comment]
> This charm is still under heavy development, as I understand it. Why publishing to something different than "latest"?

Hey, the reason for this is we have 2 versions of the haproxy charm co-existing at the same time. For now we've decided that the "legacy" charm which is at `legacy/main` will stay on `latest/*` and the new charm will be at `2.8/*` for the moment since it provides haproxy v2.8

**Review by gregory-schiano — APPROVED** [review]

**Comment by arturo-seijas** [comment]
> > This charm is still under heavy development, as I understand it. Why publishing to something different than "latest"?
> 
> Hey, the reason for this is we have 2 versions of the haproxy charm co-existing at the same time. For now we've decided that the "legacy" charm which is at `legacy/main` will stay on `latest/*` and the new charm will be at `2.8/*` for the moment since it provides haproxy v2.8

Thanks for clarifying. Would you mind adding that explanation to the PR description?

**Review by arturo-seijas — APPROVED** [review]

**Comment by Thanhphan1147** [comment]
> > > This charm is still under heavy development, as I understand it. Why publishing to something different than "latest"?
> > 
> > 
> > Hey, the reason for this is we have 2 versions of the haproxy charm co-existing at the same time. For now we've decided that the "legacy" charm which is at `legacy/main` will stay on `latest/*` and the new charm will be at `2.8/*` for the moment since it provides haproxy v2.8
> 
> Thanks for clarifying. Would you mind adding that explanation to the PR description?

Makes sense, I updated the PR description to match.

**Pull request merged**
